import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import { AuthProvider } from "@/context/AuthContext";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/layout/site-header";
import { AppSidebarDeveloper } from "@/components/layout/AppSidebarDeveloper";
import UserProvider from "../providers/UserProvider";
import RoleProtection from "@/components/common/RoleProtection";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <section className="dashboard-layout">


      <ThemeProvider>
        <UserProvider>
          <AuthProvider>
            <RoleProtection requiredRole="DEVELOPER">
              <SidebarProvider><AppSidebarDeveloper variant="inset" /><SidebarInset>{children}</SidebarInset></SidebarProvider>
            </RoleProtection>
          </AuthProvider>
        </UserProvider>
      </ThemeProvider>
    </section>
  );
}
